### ISSUE TITLE
bootme interval of 5 minutes doesn't seem to ever run HTX

### ISSUE THREAD

**Issue by stewart-ibm** [open-power/HTX#46] opened 2016-08-19 04:35 UTC
I set BOOTME to go every five minutes:
REBOOT: 0,5,10,15,20,25,30,35,40,45,50,55 *

yet I never see the big HTX in that cycle, I just get a constant reboot.

With my experimental firmware build where reboot-to-ubuntu-and-htx is around 35 seconds, a 5 minute cycle is a reasonable time.

**Comment by mehuljpatel** [comment] 2016-08-19 10:56
Duplicate of issue #45

**Closed by mehuljpatel** 2016-08-19 10:56 UTC
